### ISSUE TITLE
Webhook is not working

### ISSUE THREAD

**Issue by alinakasimova336** [ericferon/glpi-webhook#8]
Hi everybody! 
I set to get a notification when ticket is being updated. I do get notification via email and browser but not via webhook. What should I do?

**Comment by ericferon** [comment]
Hi,
Did you follow the process described in the wiki https://github.com/ericferon/glpi-webhook/wiki/Webhook ?
If yes, more information will be needed to help you.
K.r,

**Comment by gilbanech** [comment]
The plugin doesn't work for me either.
I followed the installation instructions.
i'm trying to send a message to rocket.chat
but I don't even see attempts to access the url in the nginx access log to the Rocket server.
when I make a direct curl call from the shell from the gpi server, it works.

curl -H "X-Auth-Token: <My-Token-ID>" \
                   -H "X-User-Id: <My-User-ID>" \
                   -H "Content-type:application/json" \
                   https://<My-URL-api> \
                   -d '{ "channel": "@user", "text": "This is a direct message!" }'

**Comment by ericferon** [comment]
Are you using the last version (v1.0.4) ?
Have you messages in the file /pathtoglpi/files/_log/webhook.log ?
K.r,

**Comment by gilbanech** [comment]
GLPI version: 10.0.3
Webhook plugin version: 1.0.4
no such file: /pathtoglpi/files/_log/webhook.log
I have read this issue:
https://github.com/ericferon/glpi-webhook/issues/9
and noticed that I also do not have recipients for webhook.
on the last screenshot, all recipients are added via the "All" button
![webhook1](https://user-images.githubusercontent.com/76148833/195983058-1726fd41-903d-40bf-9f16-0edd54ef7c63.png)
![webhook2](https://user-images.githubusercontent.com/76148833/195983076-b3932a0f-683f-43b7-9f35-8b4e37faf390.png)
![webhook3](https://user-images.githubusercontent.com/76148833/195983078-fbb72803-bd9d-4fe1-aec0-bfc10cdbd1d6.png)

**Comment by ericferon** [comment]
Hi,
Have you error messages related to the plugin into pathtoglpi/files/_log/php-errors.log or sql-errors.log ?
Otherwise, can you read the table glpi_plugin_webhook_configs in the GLPI database and execute the query "SELECT id, name FROM glpi_plugin_webhook_configs" ?
K.r,

**Comment by gilbanech** [comment]
Hi, there are warnings in php-errors.log on the day the plugin was installed:
`[2022-10-07 07:21:42] glpiphplog.WARNING:   *** PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_webhook_secrettypes`.`id`. in /var/www/html/src/DBmysql.php at line 2033
  plugins/webhook/hook.php:34                        DBmysql->runFile()
  src/Plugin.php:787                                 plugin_webhook_install()
  plugins/webhook/hook.php:34                        DBmysql->runFile()
  src/Plugin.php:787                                 plugin_webhook_install()
[2022-10-07 07:21:43] glpiphplog.WARNING:   *** PHP User Warning (512): Usage of signed integers in primary or foreign keys is discouraged, please use unsigned integers instead in `glpi_plugin_webhook_operationtypes`.`id`. in /var/www/html/src/DBmysql.php at line 2033
  plugins/webhook/hook.php:34                        DBmysql->runFile()
  src/Plugin.php:787                                 plugin_webhook_install()`

Query result "SELECT id, name FROM glpi_plugin_webhook_configs":

MariaDB [glpidb]> SELECT id, name FROM glpi_plugin_webhook_configs;
+----+--------+
| id | name   |
+----+--------+
|  1 | Rocket |
+----+--------+

![webhook4](https://user-images.githubusercontent.com/76148833/196168044-42767a1f-149e-434f-8404-f75b5cada45f.png)

**Comment by ericferon** [comment]
Hi,
In order to change signed integers keys into unsigned ones, you can run the command "php bin/console glpi:migration:unsigned_keys", from the GLPI root directory.
But this warning does not explain why you don't see your Rocket webhook into the list.
However, I'm surprised that you are using the v1.0.4 and that the list of "Authentication type" doesn't display "2 - Basic Authentication".
Can you run the query "SELECT id, name FROM glpi_plugin_webhook_secrettypes" ?
Thank you,

**Comment by gilbanech** [comment]
Hi, 
Query result:
MariaDB [glpidb]> SELECT id, name FROM glpi_plugin_webhook_secrettypes;
+----+------------------------------+
| id | name                         |
+----+------------------------------+
|  1 | Basic Authentication         |
|  2 | Encoded Basic Authentication |
+----+------------------------------+

![webhook5](https://user-images.githubusercontent.com/76148833/196181697-79603e68-f673-4e11-99b2-907ae44c237f.png)

**Comment by ericferon** [comment]
Hi,
There was a bug in v1.0.4 and the "Authentication type" list has not been upgraded as it should be.
Can you install v1.0.5 and run again the last query "SELECT id, name FROM glpi_plugin_webhook_secrettypes" ?
Can you also check whether your "Rocket" webhook appears in the recipient list ?
Thank you in advance,

**Comment by gilbanech** [comment]
I did everything.
but there were no recipients.
I then removed the old "Rocket" webhook and created a new "rocket".
Nothing changed
there are no errors in php-error and sql-error logs

MariaDB [glpidb]> SELECT id, name FROM glpi_plugin_webhook_configs;
+----+--------+
| id | name   |
+----+--------+
|  2 | rocket |
+----+--------+

MariaDB [glpidb]> SELECT id, name FROM glpi_plugin_webhook_secrettypes;
+----+----------------------------------+
| id | name                             |
+----+----------------------------------+
|  1 | 1 - None                         |
|  2 | 2 - Basic Authentication         |
|  3 | 3 - Encoded Basic Authentication |
+----+----------------------------------+
![webhook5_1](https://user-images.githubusercontent.com/76148833/196195201-3af38895-cbed-433d-bf2c-e29910fc86e8.png)
![webhook5_2](https://user-images.githubusercontent.com/76148833/196195205-357fcb70-c3df-4f89-a14b-c452190f3ca4.png)
all recipients selected
![webhook5_3](https://user-images.githubusercontent.com/76148833/196195206-2733c897-520f-4ee7-8ae2-795ab19e5085.png)

**Comment by peroda** [comment]
the same thing happens to me with microsoft Teams webhook

**Comment by ericferon** [comment]
There was indeed a bug, that has been solved in v1.0.6.
K.r,

**Comment by peroda** [comment]
> There was indeed a bug, that has been solved in v1.0.6. K.r,

Thanks.

**Comment by Melak91** [comment]
I have been following this issue for the past few days, Is there others step to do to see webhook in recipent cause I still can't see them.

here the step i did:
- uninstall webhook plugin (i had 1.0.4)
- download and install webhook v 1.0.6
- then I followed your wiki 
  - create webhook
  - activate webhook in notification
  - create a notification template with translation
  - create a notification 
  - Associate the new template to the new notification
  - then it's time for recipient, but there's no webhook
  

here a list of all recipient avalaible (added with all button)
![image](https://user-images.githubusercontent.com/47949153/196451855-11201cf7-ca5d-4f5a-b9d6-338e21082f43.png)

There is no error about webhook in php-error and sql-error logs

**Comment by ericferon** [comment]
Hi, @Melak91 
Which type of notification and which event do you use for your webhook (in Setup>Notifications>Notifications) ?
K.r,

**Comment by Melak91** [comment]
Hi,@ericferon

type: Form answer
event: The form as been saved

Thanks fore the help!

**Comment by ericferon** [comment]
Hi,
I've not this event in my list. Is it an event linked to a plugin ? Which one ?
K.r,
